import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ThemeInitializer } from "@/components/ThemeInitializer";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${rubik.className}  antialiased`}>
          <ThemeInitializer />
          <div className="flex flex-col">
            <Header />
            <div>{children}</div>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
